modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/ninjaguardian/Weather2Compat/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = "logo.png"
updateJSONURL = "https://raw.githubusercontent.com/ninjaguardian/Weather2Compat/refs/heads/main/update.json"
modUrl = "https://modrinth.com/mod/weather2-compat/versions"
displayURL = "https://modrinth.com/mod/weather2-compat"

[features."${mod_id}"]
javaVersion="[${java_version},)"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}.weather2.mixins.json"
requiredMods = ["weather2"]

[[mixins]]
config = "${mod_id}.sereneseasons.mixins.json"
requiredMods = ["weather2", "sereneseasons"]

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"
referralUrl = "https://neoforged.net"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "weather2"
type = "optional"
versionRange = "[${weather_version},]"
ordering = "NONE"
side = "BOTH"
referralUrl = "https://modrinth.com/mod/weather-storms-tornadoes"

[[dependencies."${mod_id}"]]
modId = "sereneseasons"
type = "optional"
versionRange = "[${sereneseasons_version},]"
ordering = "NONE"
side = "BOTH"
referralUrl = "https://modrinth.com/mod/serene-seasons"
